---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - 'echo Installing dependencies...'
      - 'npm install'
  build:
    on-failure: ABORT
    commands:
      - 'echo Building website...'
      - 'npm run build'
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
